/**
 * 每金 - laozi 類別金句
 */

export type QuoteCategory = 'humor' | 'serious' | 'lunyu' | 'zhuangzi' | 'laozi';

export interface Quote {
  id: number;
  text: string;
  category: QuoteCategory;
  explanation?: string;
  author?: string;
}

export const laoziQuotes: Quote[] = [
  {
    id: 2001,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2002,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2003,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2004,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2005,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2006,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2007,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2008,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2009,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2010,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2011,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2012,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2013,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2014,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2015,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2016,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2017,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2018,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2019,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2020,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2021,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2022,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2023,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2024,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2025,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2026,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2027,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2028,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2029,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2030,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2031,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2032,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2033,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2034,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2035,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2036,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2037,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2038,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2039,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2040,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2041,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2042,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2043,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2044,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2045,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2046,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2047,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2048,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2049,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2050,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2051,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2052,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2053,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2054,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2055,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2056,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2057,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2058,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2059,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2060,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2061,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2062,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2063,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2064,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2065,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2066,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2067,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2068,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2069,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2070,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2071,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2072,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2073,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2074,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2075,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2076,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2077,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2078,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2079,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2080,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2081,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2082,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2083,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2084,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2085,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2086,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2087,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2088,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2089,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2090,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2091,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2092,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2093,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2094,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2095,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2096,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2097,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2098,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2099,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2100,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2101,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2102,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2103,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2104,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2105,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2106,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2107,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2108,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2109,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2110,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2111,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2112,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2113,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2114,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2115,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2116,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2117,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2118,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2119,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2120,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2121,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2122,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2123,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2124,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2125,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2126,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2127,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2128,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2129,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2130,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2131,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2132,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2133,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2134,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2135,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2136,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2137,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2138,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2139,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2140,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2141,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2142,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2143,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2144,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2145,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2146,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2147,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2148,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2149,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2150,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2151,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2152,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2153,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2154,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2155,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2156,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2157,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2158,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2159,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2160,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2161,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2162,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2163,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2164,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2165,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2166,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2167,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2168,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2169,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2170,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2171,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2172,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2173,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2174,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2175,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2176,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2177,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2178,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2179,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2180,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2181,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2182,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2183,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2184,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2185,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2186,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2187,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2188,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2189,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2190,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2191,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2192,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2193,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2194,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2195,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2196,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2197,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2198,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2199,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2200,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2201,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2202,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2203,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2204,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2205,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2206,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2207,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2208,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2209,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2210,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2211,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2212,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2213,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2214,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2215,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2216,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2217,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2218,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2219,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2220,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2221,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2222,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2223,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2224,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2225,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2226,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2227,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2228,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2229,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2230,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2231,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2232,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2233,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2234,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2235,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2236,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2237,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2238,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2239,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2240,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2241,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2242,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2243,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2244,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2245,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2246,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2247,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2248,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2249,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2250,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2251,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2252,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2253,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2254,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2255,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2256,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2257,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2258,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2259,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2260,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2261,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2262,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2263,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2264,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2265,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2266,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2267,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2268,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2269,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2270,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2271,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2272,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2273,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2274,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2275,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2276,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2277,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2278,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2279,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2280,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2281,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2282,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2283,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2284,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2285,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2286,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2287,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2288,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2289,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2290,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2291,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2292,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2293,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2294,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2295,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2296,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2297,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2298,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2299,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2300,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2301,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2302,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2303,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2304,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2305,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2306,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2307,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2308,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2309,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2310,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2311,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2312,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2313,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2314,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2315,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2316,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2317,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2318,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2319,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2320,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2321,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2322,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2323,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2324,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2325,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2326,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2327,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2328,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2329,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2330,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2331,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2332,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2333,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2334,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2335,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2336,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2337,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2338,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2339,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2340,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2341,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2342,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2343,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2344,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2345,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2346,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2347,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2348,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2349,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2350,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2351,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2352,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2353,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2354,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2355,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2356,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2357,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2358,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2359,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2360,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2361,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2362,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2363,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2364,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2365,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2366,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2367,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2368,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2369,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2370,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2371,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2372,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2373,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2374,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2375,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2376,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2377,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2378,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2379,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2380,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2381,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2382,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2383,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2384,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2385,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2386,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2387,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2388,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2389,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2390,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2391,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2392,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2393,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2394,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2395,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2396,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2397,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2398,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2399,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2400,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2401,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2402,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2403,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2404,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2405,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2406,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2407,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2408,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2409,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2410,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2411,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2412,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2413,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2414,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2415,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2416,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2417,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2418,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2419,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2420,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2421,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2422,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2423,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2424,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2425,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2426,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2427,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2428,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2429,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2430,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2431,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2432,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2433,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2434,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2435,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2436,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2437,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2438,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2439,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2440,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2441,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2442,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2443,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2444,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2445,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2446,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2447,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2448,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2449,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2450,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2451,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2452,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2453,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2454,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2455,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2456,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2457,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2458,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2459,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2460,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2461,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2462,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2463,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2464,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2465,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2466,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2467,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2468,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2469,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2470,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2471,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2472,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2473,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2474,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2475,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2476,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2477,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2478,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2479,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2480,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2481,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2482,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2483,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2484,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2485,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2486,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2487,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2488,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2489,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2490,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2491,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2492,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2493,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2494,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2495,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
  {
    id: 2496,
    text: '道可道，非常道',
    category: 'laozi',
    explanation: '能用言語表達的道，就不是永恆不變的道',
    author: '老子',
  },
  {
    id: 2497,
    text: '無為而治',
    category: 'laozi',
    explanation: '不刻意作為就能治理天下',
    author: '老子',
  },
  {
    id: 2498,
    text: '上善若水',
    category: 'laozi',
    explanation: '最高的善就像水一樣，柔和而無所不在',
    author: '老子',
  },
  {
    id: 2499,
    text: '知足常樂',
    category: 'laozi',
    explanation: '懂得知足的人常常感到快樂',
    author: '老子',
  },
  {
    id: 2500,
    text: '返璞歸真',
    category: 'laozi',
    explanation: '回歸本真，去除虛偽',
    author: '老子',
  },
];
