/**
 * 每金 - lunyu 類別金句
 */

export type QuoteCategory = 'humor' | 'serious' | 'lunyu' | 'zhuangzi' | 'laozi';

export interface Quote {
  id: number;
  text: string;
  category: QuoteCategory;
  explanation?: string;
  author?: string;
}

export const lunyuQuotes: Quote[] = [
  {
    id: 1001,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1002,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1003,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1004,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1005,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1006,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1007,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1008,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1009,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1010,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1011,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1012,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1013,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1014,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1015,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1016,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1017,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1018,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1019,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1020,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1021,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1022,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1023,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1024,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1025,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1026,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1027,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1028,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1029,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1030,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1031,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1032,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1033,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1034,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1035,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1036,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1037,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1038,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1039,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1040,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1041,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1042,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1043,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1044,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1045,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1046,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1047,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1048,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1049,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1050,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1051,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1052,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1053,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1054,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1055,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1056,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1057,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1058,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1059,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1060,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1061,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1062,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1063,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1064,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1065,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1066,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1067,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1068,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1069,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1070,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1071,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1072,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1073,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1074,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1075,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1076,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1077,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1078,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1079,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1080,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1081,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1082,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1083,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1084,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1085,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1086,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1087,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1088,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1089,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1090,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1091,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1092,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1093,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1094,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1095,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1096,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1097,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1098,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1099,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1100,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1101,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1102,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1103,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1104,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1105,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1106,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1107,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1108,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1109,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1110,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1111,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1112,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1113,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1114,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1115,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1116,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1117,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1118,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1119,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1120,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1121,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1122,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1123,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1124,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1125,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1126,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1127,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1128,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1129,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1130,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1131,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1132,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1133,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1134,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1135,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1136,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1137,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1138,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1139,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1140,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1141,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1142,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1143,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1144,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1145,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1146,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1147,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1148,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1149,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1150,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1151,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1152,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1153,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1154,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1155,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1156,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1157,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1158,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1159,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1160,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1161,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1162,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1163,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1164,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1165,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1166,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1167,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1168,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1169,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1170,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1171,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1172,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1173,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1174,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1175,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1176,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1177,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1178,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1179,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1180,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1181,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1182,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1183,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1184,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1185,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1186,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1187,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1188,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1189,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1190,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1191,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1192,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1193,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1194,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1195,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1196,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1197,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1198,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1199,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1200,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1201,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1202,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1203,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1204,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1205,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1206,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1207,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1208,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1209,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1210,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1211,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1212,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1213,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1214,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1215,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1216,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1217,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1218,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1219,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1220,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1221,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1222,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1223,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1224,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1225,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1226,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1227,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1228,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1229,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1230,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1231,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1232,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1233,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1234,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1235,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1236,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1237,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1238,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1239,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1240,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1241,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1242,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1243,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1244,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1245,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1246,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1247,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1248,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1249,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1250,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1251,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1252,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1253,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1254,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1255,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1256,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1257,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1258,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1259,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1260,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1261,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1262,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1263,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1264,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1265,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1266,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1267,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1268,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1269,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1270,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1271,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1272,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1273,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1274,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1275,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1276,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1277,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1278,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1279,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1280,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1281,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1282,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1283,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1284,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1285,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1286,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1287,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1288,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1289,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1290,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1291,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1292,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1293,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1294,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1295,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1296,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1297,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1298,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1299,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1300,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1301,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1302,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1303,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1304,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1305,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1306,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1307,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1308,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1309,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1310,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1311,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1312,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1313,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1314,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1315,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1316,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1317,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1318,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1319,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1320,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1321,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1322,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1323,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1324,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1325,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1326,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1327,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1328,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1329,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1330,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1331,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1332,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1333,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1334,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1335,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1336,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1337,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1338,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1339,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1340,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1341,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1342,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1343,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1344,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1345,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1346,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1347,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1348,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1349,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1350,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1351,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1352,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1353,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1354,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1355,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1356,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1357,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1358,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1359,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1360,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1361,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1362,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1363,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1364,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1365,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1366,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1367,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1368,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1369,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1370,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1371,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1372,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1373,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1374,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1375,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1376,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1377,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1378,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1379,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1380,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1381,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1382,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1383,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1384,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1385,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1386,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1387,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1388,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1389,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1390,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1391,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1392,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1393,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1394,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1395,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1396,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1397,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1398,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1399,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1400,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1401,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1402,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1403,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1404,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1405,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1406,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1407,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1408,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1409,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1410,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1411,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1412,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1413,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1414,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1415,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1416,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1417,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1418,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1419,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1420,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1421,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1422,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1423,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1424,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1425,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1426,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1427,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1428,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1429,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1430,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1431,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1432,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1433,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1434,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1435,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1436,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1437,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1438,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1439,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1440,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1441,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1442,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1443,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1444,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1445,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1446,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1447,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1448,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1449,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1450,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1451,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1452,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1453,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1454,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1455,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1456,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1457,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1458,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1459,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1460,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1461,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1462,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1463,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1464,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1465,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1466,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1467,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1468,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1469,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1470,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1471,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1472,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1473,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1474,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1475,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1476,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1477,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1478,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1479,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1480,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1481,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1482,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1483,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1484,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1485,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1486,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1487,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1488,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1489,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1490,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1491,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1492,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1493,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1494,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1495,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
  {
    id: 1496,
    text: '學而時習之，不亦說乎？',
    category: 'lunyu',
    explanation: '學習知識後，經常複習練習，不是很快樂嗎？',
    author: '孔子',
  },
  {
    id: 1497,
    text: '溫故而知新，可以為師矣。',
    category: 'lunyu',
    explanation: '溫習舊知識而能領悟新的道理，就可以成為老師了。',
    author: '孔子',
  },
  {
    id: 1498,
    text: '知之為知之，不知為不知，是知也。',
    category: 'lunyu',
    explanation: '知道就是知道，不知道就是不知道，這才是真正的智慧。',
    author: '孔子',
  },
  {
    id: 1499,
    text: '三人行，必有我師焉。',
    category: 'lunyu',
    explanation: '三個人一起行走，其中必有值得我學習的人。',
    author: '孔子',
  },
  {
    id: 1500,
    text: '己所不欲，勿施於人。',
    category: 'lunyu',
    explanation: '自己不想要的東西，就不要強加給別人。',
    author: '孔子',
  },
];
