/**
 * 每金 - zhuangzi 類別金句
 */

export type QuoteCategory = 'humor' | 'serious' | 'lunyu' | 'zhuangzi' | 'laozi';

export interface Quote {
  id: number;
  text: string;
  category: QuoteCategory;
  explanation?: string;
  author?: string;
}

export const zhuangziQuotes: Quote[] = [
  {
    id: 1501,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1502,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1503,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1504,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1505,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1506,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1507,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1508,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1509,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1510,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1511,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1512,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1513,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1514,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1515,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1516,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1517,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1518,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1519,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1520,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1521,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1522,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1523,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1524,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1525,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1526,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1527,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1528,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1529,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1530,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1531,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1532,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1533,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1534,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1535,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1536,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1537,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1538,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1539,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1540,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1541,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1542,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1543,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1544,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1545,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1546,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1547,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1548,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1549,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1550,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1551,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1552,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1553,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1554,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1555,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1556,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1557,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1558,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1559,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1560,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1561,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1562,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1563,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1564,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1565,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1566,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1567,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1568,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1569,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1570,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1571,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1572,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1573,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1574,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1575,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1576,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1577,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1578,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1579,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1580,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1581,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1582,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1583,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1584,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1585,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1586,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1587,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1588,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1589,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1590,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1591,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1592,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1593,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1594,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1595,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1596,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1597,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1598,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1599,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1600,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1601,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1602,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1603,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1604,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1605,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1606,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1607,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1608,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1609,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1610,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1611,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1612,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1613,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1614,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1615,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1616,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1617,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1618,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1619,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1620,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1621,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1622,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1623,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1624,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1625,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1626,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1627,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1628,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1629,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1630,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1631,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1632,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1633,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1634,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1635,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1636,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1637,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1638,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1639,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1640,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1641,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1642,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1643,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1644,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1645,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1646,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1647,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1648,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1649,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1650,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1651,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1652,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1653,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1654,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1655,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1656,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1657,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1658,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1659,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1660,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1661,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1662,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1663,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1664,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1665,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1666,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1667,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1668,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1669,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1670,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1671,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1672,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1673,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1674,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1675,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1676,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1677,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1678,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1679,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1680,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1681,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1682,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1683,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1684,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1685,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1686,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1687,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1688,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1689,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1690,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1691,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1692,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1693,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1694,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1695,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1696,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1697,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1698,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1699,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1700,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1701,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1702,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1703,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1704,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1705,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1706,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1707,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1708,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1709,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1710,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1711,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1712,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1713,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1714,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1715,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1716,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1717,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1718,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1719,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1720,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1721,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1722,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1723,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1724,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1725,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1726,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1727,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1728,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1729,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1730,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1731,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1732,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1733,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1734,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1735,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1736,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1737,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1738,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1739,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1740,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1741,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1742,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1743,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1744,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1745,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1746,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1747,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1748,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1749,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1750,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1751,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1752,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1753,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1754,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1755,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1756,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1757,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1758,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1759,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1760,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1761,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1762,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1763,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1764,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1765,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1766,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1767,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1768,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1769,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1770,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1771,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1772,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1773,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1774,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1775,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1776,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1777,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1778,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1779,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1780,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1781,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1782,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1783,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1784,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1785,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1786,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1787,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1788,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1789,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1790,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1791,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1792,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1793,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1794,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1795,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1796,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1797,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1798,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1799,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1800,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1801,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1802,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1803,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1804,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1805,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1806,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1807,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1808,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1809,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1810,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1811,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1812,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1813,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1814,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1815,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1816,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1817,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1818,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1819,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1820,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1821,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1822,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1823,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1824,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1825,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1826,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1827,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1828,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1829,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1830,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1831,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1832,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1833,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1834,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1835,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1836,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1837,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1838,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1839,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1840,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1841,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1842,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1843,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1844,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1845,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1846,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1847,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1848,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1849,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1850,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1851,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1852,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1853,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1854,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1855,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1856,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1857,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1858,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1859,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1860,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1861,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1862,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1863,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1864,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1865,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1866,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1867,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1868,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1869,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1870,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1871,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1872,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1873,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1874,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1875,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1876,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1877,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1878,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1879,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1880,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1881,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1882,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1883,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1884,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1885,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1886,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1887,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1888,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1889,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1890,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1891,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1892,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1893,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1894,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1895,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1896,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1897,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1898,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1899,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1900,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1901,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1902,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1903,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1904,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1905,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1906,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1907,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1908,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1909,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1910,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1911,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1912,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1913,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1914,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1915,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1916,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1917,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1918,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1919,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1920,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1921,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1922,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1923,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1924,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1925,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1926,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1927,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1928,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1929,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1930,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1931,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1932,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1933,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1934,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1935,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1936,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1937,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1938,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1939,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1940,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1941,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1942,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1943,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1944,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1945,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1946,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1947,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1948,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1949,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1950,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1951,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1952,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1953,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1954,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1955,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1956,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1957,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1958,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1959,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1960,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1961,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1962,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1963,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1964,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1965,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1966,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1967,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1968,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1969,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1970,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1971,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1972,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1973,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1974,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1975,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1976,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1977,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1978,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1979,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1980,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1981,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1982,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1983,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1984,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1985,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1986,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1987,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1988,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1989,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1990,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1991,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1992,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1993,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1994,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 1995,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
  {
    id: 1996,
    text: '逍遙遊於天地之間',
    category: 'zhuangzi',
    explanation: '自由自在地遊歷於天地之間',
    author: '莊子',
  },
  {
    id: 1997,
    text: '道法自然',
    category: 'zhuangzi',
    explanation: '道遵循自然的規律',
    author: '莊子',
  },
  {
    id: 1998,
    text: '無為而無不為',
    category: 'zhuangzi',
    explanation: '不刻意作為，反而能成就一切',
    author: '莊子',
  },
  {
    id: 1999,
    text: '齧缺問王倪',
    category: 'zhuangzi',
    explanation: '齧缺向王倪請教人生的道理',
    author: '莊子',
  },
  {
    id: 2000,
    text: '吾生也有涯，而知也無涯',
    category: 'zhuangzi',
    explanation: '我的生命是有限的，但知識是無限的',
    author: '莊子',
  },
];
